meta_product_name: "UNIVOS"
meta_title: "UNIVOS - Do sh*t together"
meta_description: "Find activities and people to do them with you"
meta_image: "u.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
